<?php
namespace App;

// // This file is autogenerated by running 'composer dump-router-bootstrap'. Do not edit!!!
// // === View Routes === //
// router()->get('/auth/login', require(__DIR__ . '/Views/auth/login.php'));
// router()->get('/auth/logout', require(__DIR__ . '/Views/auth/logout.php'));
// router()->get('/auth/signup', require(__DIR__ . '/Views/auth/signup.php'));
// // router()->get('/', require(__DIR__ . '/Views/./index.php'));


// // === Api Routes === //
// router()->post('/api/auth/login', require(__DIR__ . '/api/auth/login/post.php'));
// router()->post('/api/auth/signup', require(__DIR__ . '/api/auth/signup/post.php'));
// router()->get('/api/sections', require(__DIR__ . '/api/sections/get.php'));
