<?php
require dirname(__DIR__) . "/vendor/autoload.php";

use Lazervel\Path\Path;

function relative(string $from, string $to): string
{
    return Path::relative($from, $to);
}

function win2unix(string $path): string
{
    return str_replace("\\", "/", $path);
}

function findPhpFiles(string $dir): array
{
    $rii = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS)
    );

    $files = [];
    foreach ($rii as $file) {
        if ($file->getExtension() === 'php') {
            $files[] = $file->getPathname();
        }
    }

    return $files;
}

function main()
{
    $viewDir = realpath(dirname(__DIR__) . "/src/Views");
    $apiDir = realpath(dirname(__DIR__) . "/src/Api");
    $routerBootstrapCode = "<?php\nnamespace App;\n\n// This file is autogenerated by running 'composer dump-router-bootstrap'. Do not edit!!!\n";

    $views = findPhpFiles($viewDir);
    $apis = findPhpFiles($apiDir);

    $viewRoutes = [];
    foreach ($views as $view) {
        $relative = win2unix(relative($viewDir, $view));
        $baseName = basename($relative);

        // Skip underscore-prefixed files (like _layout.php) and dashboard views
        if ($baseName === "_layout.php") {
            continue;
        }

        if ($relative === 'index.php' || strpos($relative, 'auth/') === 0) {
            $viewRoutes[] = $view;
        }
    }

    if (count($viewRoutes) > 0) {
        $routerBootstrapCode .= "// === View Routes === //\n";
        foreach ($viewRoutes as $view) {
            $relative = win2unix(relative($viewDir, $view));
            $relativeDir = dirname($relative);
            $baseName = basename($relative);
            // Remove .php extension from route path
            $routePath = '/' . preg_replace('/\.php$/', '', $relative);
            // Convert /index to / for the home route
            if ($routePath === '/index') {
                $routePath = '/';
            }
            $routerBootstrapCode .=
                "router()->get('$routePath', function(\$request, \$request) { return view(__DIR__ . '/Views/$relativeDir/$baseName', [])->render() };\n";
        }

        $routerBootstrapCode .= "\n\n";
    }

    if (count($apis) > 0) {
        $routerBootstrapCode .= "// === Api Routes === //\n";

        foreach ($apis as $api) {
            $method = basename($api, ".php");
            $apiRoutePath = dirname($api);
            $relativeApiRoutePath = win2unix(relative($apiDir, $apiRoutePath));

            $routerBootstrapCode .=
                "router()->$method('/api/$relativeApiRoutePath', require(__DIR__ . '/api/$relativeApiRoutePath/$method.php'));\n";
        }
    }

    $routerBootstrapFile = fopen(dirname(__DIR__) . "/src/routes.php", 'w');
    fwrite($routerBootstrapFile, $routerBootstrapCode);
    fclose($routerBootstrapFile);
}

main();